### ISSUE TITLE
Adjust URL to our new Adfinis URL

### ISSUE THREAD

**Issue by shurik-io** [adfinis-sygroup/vault-playground#29]
Hi Folks

I'm not sure, but I assume we need to change the URL to https://github.com/adfinis. I'm not too familiar with the GitHub Workflow/Actions config, thus I'm asking before I start to change something. Happy to contribute it.

https://github.com/adfinis/vault-playground/blob/5c4967df58e319f65bcc2cdd9d19d1f400c0ba81/.github-example-workflow/workflows/vault.yml#L24

Cheers

**Comment by ghost** [comment]
Thanks @shurik-io for your contribution.

Would you mind reviewing the attached PR?
