### ISSUE TITLE
Consider using IPA DNS Server

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/vault-playground#5]
* Use static IPs
* Register the names in the IPA DNS for domain resolution

**Comment by smirta** [comment]
I went down this rabbit hole this afternoon. There doesn't seem to be an elegant way to solve this using docker/podman. The only thing that would work is using docker.internal or dns.podman as domain. I'd suggest we leave this as it is and focus on https://github.com/adfinis-sygroup/vault-playground/issues/7 .
